### ISSUE TITLE
[YSQL] GCC fails to build after 634567d

### ISSUE THREAD

**Issue by es1024** [yugabyte/yugabyte-db#25658]
Jira Link: [DB-14918](https://yugabyte.atlassian.net/browse/DB-14918)
### Description

GCC fails to build after https://github.com/yugabyte/yugabyte-db/commit/634567d1a9b49a414cbfd5cb1f5ab5aac0821acb with:
```
[2025-01-16T17:19:09.962Z] /-------------------------------------------------------------------------------
[2025-01-16T17:19:09.962Z] | COMPILATION FAILED
[2025-01-16T17:19:09.962Z] |-------------------------------------------------------------------------------
[2025-01-16T17:19:09.962Z] ../../../../../../../src/postgres/src/backend/utils/misc/yb_query_diagnostics.c:126:49: error: missing braces around initializer [-Werror=missing-braces]
[2025-01-16T17:19:09.962Z]   126 | static QueryConstantsMetadata query_constants = {0, 0, {0}};
[2025-01-16T17:19:09.962Z]       |                                                 ^
[2025-01-16T17:19:09.962Z]       |                                                         {}
[2025-01-16T17:19:09.962Z] cc1: all warnings being treated as errors
[2025-01-16T17:19:09.962Z] 
[2025-01-16T17:19:09.962Z] Input files:
[2025-01-16T17:19:09.962Z]   /share/jenkins/workspace/yugabyte-db-phabricator/yugabyte-db/build/fastdebug-gcc11-dynamic-ninja/postgres_build/src/backend/utils/misc/yb_query_diagnostics.c
[2025-01-16T17:19:09.962Z] Output file (from -o): yb_query_diagnostics.o
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [x] I confirm this issue does not contain any sensitive information.

[DB-14918]: https://yugabyte.atlassian.net/browse/DB-14918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
