### ISSUE TITLE
build: fix compilation on fastdebug gcc13

### ISSUE THREAD

**Issue by jasonyb** [yugabyte/yugabyte-db#19961]
### Description

`./yb_build.sh fastdebug --gcc13` on master commit 820defddd91aefa796c189cbbed160bc435cda68 on ubuntu:23.04 docker image fails at this step.  There may be more failing areas beyond this.  It looks like this code was introduced by commit dc68e117edacbbdfa3b5c37f3283b2554b128889.

`    inlined from 'void yb::consensus::RetryableRequests::Impl::CopyFrom(const yb::consensus::RetryableRequests::Impl&)' at /home/alice/code/yugabyte-db/src/yb/consensus/retryable_requests.cc:386:37:
/usr/include/c++/13/bits/alloc_traits.h:360:23: error: pointer may be used after 'void operator delete(void*, std::size_t)' [-Werror=use-after-free]`

More logs:

https://gist.githubusercontent.com/jasonyb/2519dd71d00bb0cfa454236da81f7c9b/raw/26c29fc70c123f0aebc682a91257692f1a698b0d/gistfile1.txt

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by rthallamko3** [comment]
@jasonyb , Is this still an issue?

**Comment by jasonyb** [comment]
I don't know since I don't use this setup.  I provided the repro instructions.
