### ISSUE TITLE
Compile failure

### ISSUE THREAD

**Issue by hengestone** [YugaByte/yugabyte-db#122]
Building on Ubuntu 17.10 with `./yb_build.sh release --with-assembly` fails with:
```
/-------------------------------------------------------------------------------
| COMPILATION FAILED
|-------------------------------------------------------------------------------
src/yb/util/logging.cc: In function ‘void yb::DisableCoreDumps()’:
src/yb/util/logging.cc:355:10: error: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Werror=unused-result]
     write(f, "00000000", 8);
     ~~~~~^~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

Input files:
  src/yb/util/logging.cc

Output file (from -o): CMakeFiles/yb_util.dir/logging.cc.o
\-------------------------------------------------------------------------------
src/yb/util/CMakeFiles/yb_util.dir/build.make:974: recipe for target 'src/yb/util/CMakeFiles/yb_util.dir/logging.cc.o' failed
make[2]: *** [src/yb/util/CMakeFiles/yb_util.dir/logging.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:13265: recipe for target 'src/yb/util/CMakeFiles/yb_util.dir/all' failed
make[1]: *** [src/yb/util/CMakeFiles/yb_util.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
```

Looks like a trivial fix.

**Comment by kmuthukk** [comment]
@hectorgcr : could you help on this one?

**Comment by hectorgcr** [comment]
It should work on Ubuntu 17.10 now.
