### ISSUE TITLE
[OpenDocDB] Extension fails to build in ubuntu22.04-clang19-debug

### ISSUE THREAD

**Issue by hari90** [yugabyte/yugabyte-db#26948]
### Description

Build error:

```
[2025-04-24T06:08:34.584Z] -- CMAKE_SYSTEM_INFO_FILE: Platform/Linux
[2025-04-24T06:08:34.584Z] -- CMAKE_SYSTEM_NAME:      Linux
[2025-04-24T06:08:34.584Z] -- CMAKE_SYSTEM_PROCESSOR: x86_64
[2025-04-24T06:08:34.584Z] -- CMAKE_SYSTEM:           Linux-6.8.0-1026-gcp
[2025-04-24T06:08:34.584Z] -- CMAKE_VERSION:          3.31.0


[2025-04-24T06:31:23.782Z] /-------------------------------------------------------------------------------
[2025-04-24T06:31:23.782Z] | COMPILATION FAILED
[2025-04-24T06:31:23.782Z] |-------------------------------------------------------------------------------
[2025-04-24T06:31:23.782Z] /share/jenkins/workspace/yugabyte-db-phabricator/yugabyte-db/src/postgres/third-party-extensions/documentdb/pg_documentdb_core/src/types/pcre_regex.c:18:10: fatal error: 'pcre2.h' file not found
[2025-04-24T06:31:23.782Z]    18 | #include <pcre2.h>
[2025-04-24T06:31:23.782Z]       |          ^~~~~~~~~
[2025-04-24T06:31:23.782Z] 1 error generated.
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [x] I confirm this issue does not contain any sensitive information.
