### ISSUE TITLE
[YSQL] alter table drop constraint with 'if exists' is failing, instead of ignoring error when constraint does not exists.

### ISSUE THREAD

**Issue by sonalsagarwal** [yugabyte/yugabyte-db#14566]
Jira Link: [DB-3946](https://yugabyte.atlassian.net/browse/DB-3946)
### Description

In tpcc, we have a method _enableForeignKeys_, which creates FKs after data is loaded. In this method, drop constraint with 'if exists' is giving ERROR, causing this statement to fail, and as a result other alter statements in the code(that create FKs) were not executed.
**Error:**
```
"02:38:33,081 (DBWorkload.java:362) INFO  - Loading data into TPCC database with 48 threads...", 
"10:13:27,402 (SchemaManager.java:29) INFO  - ALTER TABLE DISTRICT DROP CONSTRAINT IF EXISTS D_FKEY_W", 
"10:13:27,454 (Loader.java:223) ERROR - Could not create foreign keysERROR: constraint \"d_fkey_w\" for table \"district\" does not exist", 
"10:13:27,455 (DBWorkload.java:366) INFO  - Finished!", 
"10:13:27,455 (DBWorkload.java:367) INFO  - 
```
**In 2.15.3.0-b56**, drop constraint with if exists gives a NOTICE if constraint does not exists.
```
yugabyte=# ALTER TABLE contacts drop  CONSTRAINT IF EXISTS D_FKEY_W;
NOTICE:  constraint "d_fkey_w" of relation "contacts" does not exist, skipping
ALTER TABLE
```
**In 2.15.3.0-b107**, drop constraint with if exists gives ERROR if constraint does not exists, causing the failure, which results in non-execution of the other alter statements.
```
yugabyte=# ALTER TABLE contacts drop  CONSTRAINT IF EXISTS D_FKEY_W;
ERROR:  constraint "d_fkey_w" for table "contacts" does not exist
So, some changes between 2.15.3.0-b56 and 2.15.3.0-b107 has triggered the issue. 
```
This ERROR seems to be a bug in the product, as with if exists, any error for non-existing constraints should be ignored.

**Comment by m-iancu** [comment]
Superficially, looks like this might have been introduced in https://github.com/yugabyte/yugabyte-db/commit/76a39035a8c3aa3a4f0bd63f2aa43fe236135170. Specifically this new code: https://github.com/YugaByte/yugabyte-db/blob/master/src/postgres/src/backend/commands/ybccmds.c#L1283-L1285 passes the third argument to `get_relation_constraint_oid` (`missing_ok`) as always `false`.

**Comment by MrEasy** [comment]
anyone knowing of a workaround?
btw. ``CREATE EXTENSION`IF NOT EXIST`` is working fine.

**Comment by fizaaluthra** [comment]
Duplicate of #17659
