### ISSUE TITLE
src/yb/util/format.h: Release 2.2.2.0 compilation regression on gcc 7.5.0

### ISSUE THREAD

**Issue by LINKIWI** [yugabyte/yugabyte-db#5528]
We're observing the following build failure (compilation warning treated as error) while building on Ubuntu 18.04 with gcc 7.5.0 at release tag 2.2.2.0:

```
( cd "/opt/yugabyte-db/build/release-gcc-dynamic-ninja" && YB_THIRDPARTY_DIR=/opt/yugabyte-db/thirdparty /usr/bin/g++ -Dyb_pggate_EXPORTS -Isrc -I../../ent/src -I../../src -isystem ../../thirdparty/installed/common/include -isystem ../../thirdparty/installed/uninstrumented/include -Ipostgres_build/src/include -Werror -fno-strict-aliasing -msse4.2 -Wall -Wno-sign-compare -Wno-deprecated -Winvalid-pch -pthread -DBOOST_BIND_NO_PLACEHOLDERS -DBOOST_UUID_RANDOM_PROVIDER_FORCE_POSIX -DROCKSDB_PLATFORM_POSIX -DROCKSDB_USING_THREAD_STATUS=0 -DBOOST_ERROR_CODE_HEADER_ONLY -march=ivybridge -mcx16 -DYB_COMPILER_TYPE=gcc -DYB_COMPILER_VERSION=7.5.0 -DROCKSDB_LIB_IO_POSIX -DSNAPPY -DZLIB -mno-avx -mno-bmi -mno-bmi2 -mno-fma -D__STDC_FORMAT_MACROS -Wno-deprecated-declarations -DGFLAGS=gflags -Wnon-virtual-dtor -Werror=enum-compare -Werror=reorder -Werror=switch -Werror=return-type -Werror=non-virtual-dtor -DYB_HEADERS_NO_STUBS=1 -O3 -g -DNDEBUG -fno-omit-frame-pointer -mno-abm -mno-movbe -fPIC -DTCMALLOC_ENABLED -faligned-new -fPIC -std=gnu++14 -MD -MT src/yb/yql/pggate/CMakeFiles/yb_pggate.dir/pg_doc_op.cc.o -MF src/yb/yql/pggate/CMakeFiles/yb_pggate.dir/pg_doc_op.cc.o.d -o src/yb/yql/pggate/CMakeFiles/yb_pggate.dir/pg_doc_op.cc.o -c ../../src/yb/yql/pggate/pg_doc_op.cc )  # Compiler exit code: 1./-------------------------------------------------------------------------------
| COMPILATION FAILED
|-------------------------------------------------------------------------------
In file included from src/yb/util/status.h:49:0,
                 from src/yb/util/errno.h:37,
                 from src/yb/util/locks.h:46,
                 from src/yb/yql/pggate/pg_doc_op.h:22,
                 from src/yb/yql/pggate/pg_doc_op.cc:15:
src/yb/util/format.h: In function ‘std::__cxx11::string yb::internal::FormatImpl(const char*, const Args& ...) [with Args = {char [32], char*, std::nullptr_t}]’:
src/yb/util/format.h:84:68: error: argument 1 null where non-null expected [-Werror=nonnull]
   explicit FormatValue(const U& value) : value_(value), len_(strlen(value_)) {}
                                                              ~~~~~~^~~~~~~~
In file included from thirdparty/installed/uninstrumented/include/glog/logging.h:40:0,
                 from src/yb/util/locks.h:38,
                 from src/yb/yql/pggate/pg_doc_op.h:22,
                 from src/yb/yql/pggate/pg_doc_op.cc:15:
/usr/include/string.h:384:15: note: in a call to function ‘size_t strlen(const char*)’ declared here
 extern size_t strlen (const char *__s)
               ^~~~~~
cc1plus: all warnings being treated as errorsInput files:
  src/yb/yql/pggate/CMakeFiles/yb_pggate.dir/pg_doc_op.cc.o
  src/yb/yql/pggate/pg_doc_op.cc
Output file (from -o): src/yb/yql/pggate/CMakeFiles/yb_pggate.dir/pg_doc_op.cc.o
\-------------------------------------------------------------------------------
[1168/1734] Building CXX object src/yb/yql/cql/ql/parser/CMakeFiles/ql_parser.dir/parser_gram.y.final.cc.o
ninja: build stopped: subcommand failed.
```

Reproduction steps: Follow Ubuntu instructions at https://docs.yugabyte.com/latest/contribute/core-database/build-from-src-ubuntu/
Namely, install dev dependencies via APT and run `./yb_build.sh release`

I believe this is a regression introduced by 3cc2e340ddfa7a7eab2c0a9f97e5318b30ec5057.

**Comment by d-uspenskiy** [comment]
Duplicate https://github.com/yugabyte/yugabyte-db/issues/5209
