### ISSUE TITLE
[YSQL][Colocation] FATAL: Check failed: colocation_it != kv_store_.colocation_to_table.end() during drop table

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#13760]
Jira Link: [DB-3286](https://yugabyte.atlassian.net/browse/DB-3286)
### Description

itest-system's upgrade test started failing in https://phabricator.dev.yugabyte.com/D19079, which adds a `drop table` after upgrade from 2.12.4.2-b1 to 2.15.3.0-b77. The tables are colocated. There is a similar bug with tablegroups at https://github.com/yugabyte/yugabyte-db/issues/13317, which might have the same root cause. @frozenspider should this be considered a duplicate?
Test failure:
```
2022-08-24 15:13:58,087 test_base.py:163 ERROR testupgrade-aws-rf3-upgrade-2.12.4.2_1 ITEST FAILED testupgrade-aws-rf3-upgrade-2.12.4.2_1 : AdminShutdown('terminating connection due to administrator command\nserver closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n')
2022-08-24 15:13:58,088 test_base.py:164 INFO testupgrade-aws-rf3-upgrade-2.12.4.2_1 Traceback (most recent call last):
  File "/var/lib/jenkins/code/internal-services/itest/src/test_base.py", line 159, in execute_steps
    step.call()
  File "/var/lib/jenkins/code/internal-services/itest/src/test_base.py", line 51, in call
    ret = self.function()
  File "/var/lib/jenkins/code/internal-services/itest/src/universe_tests/system_tests/test_upgrade.py", line 148, in do_custom_work
    self.drop_ysql_objects(universe, release_version)
  File "/var/lib/jenkins/code/internal-services/itest/src/universe_tests/system_tests/test_upgrade.py", line 270, in drop_ysql_objects
    session.execute(query)
psycopg2.errors.AdminShutdown: terminating connection due to administrator command
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```
```
F20220824 15:13:58 ../../src/yb/tablet/tablet_metadata.cc:850] Check failed: colocation_it != kv_store_.colocation_to_table.end()
    @          0x2a74fc8  google::LogMessage::SendToLog()
    @          0x2a75e73  google::LogMessage::Flush()
    @          0x2a763ff  google::LogMessageFatal::~LogMessageFatal()
    @          0x36519bf  yb::tablet::RaftGroupMetadata::SetSchema()
    @          0x360d80d  yb::tablet::Tablet::AlterSchema()
    @          0x35ce0cb  yb::tablet::ChangeMetadataOperation::DoReplicated()
    @          0x35d06df  yb::tablet::Operation::Replicated()
    @          0x35d1b1e  yb::tablet::OperationDriver::ReplicationFinished()
    @          0x2e876b5  yb::consensus::ConsensusRound::NotifyReplicationFinished()
    @          0x2ed603b  yb::consensus::ReplicaState::ApplyPendingOperationsUnlocked()
    @          0x2ed543d  yb::consensus::ReplicaState::AdvanceCommittedOpIdUnlocked()
    @          0x2eb2de7  yb::consensus::RaftConsensus::UpdateMajorityReplicated()
    @          0x2e7d0b1  yb::consensus::PeerMessageQueue::NotifyObserversOfMajorityReplOpChangeTask()
    @          0x3b42211  yb::ThreadPool::DispatchThread()
    @          0x3b3d9a1  yb::Thread::SuperviseThread()
    @     0x7f734519e694  start_thread
    @     0x7f73456a041d  __clone
```
On a side note, when I don't drop the tables and restore the backup, I noticed that the backup is actually not restored, which is why added the drop. I guess this is also unexpected?

**Comment by frozenspider** [comment]
I'm pretty sure this is a duplicate, but I'm not sure how would I repro it.
One option would be to check itests after a fix for #13317 lands.

**Comment by frozenspider** [comment]
@def-, since #13317 is resolved now, would it be possible to re-check this?

**Comment by def-** [comment]
Sure, will do when a build is available with the fix, 2.15.3.0-b169 I guess.

**Comment by def-** [comment]
The drop table is not failing anymore. I have new failures now, will investigate.
