### ISSUE TITLE
cpp-driver Fails to compile on Ubuntu 18.04 

### ISSUE THREAD

**Issue by ajcaldera1** [YugaByte/yugabyte-db#1092]
When compiling the cpp-driver on Ubuntu 18.04 (GCC version 7.30 - Ubuntu 7.3.0-27ubuntu1-18.04), errors are thrown in src/jenkins_hash.cpp unless [-Werror=implicit-fallthrough=] is commented out. 
```
/tmp/cpp-driver/src/jenkins_hash.cpp:136:9: error: this statement may fall through [-Werror=implicit-fallthrough=]
       c += char2unsigned64(s[22]) << 56;
       ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by kmuthukk** [comment]
The user also reported that << if I take out the -Werror flag in a couple of places in cmake/modules/CppDriver.cmake it builds >>

**Comment by OlegLoginov** [comment]
Fixed (in branch 2.9.0-yb). 
https://github.com/YugaByte/cassandra-cpp-driver/commit/ef201ce89dc03f5856dde18d481bf8f38b80a06d

**Comment by OlegLoginov** [comment]
Tag 2.9.0-yb-5
https://github.com/YugaByte/cassandra-cpp-driver/releases/tag/2.9.0-yb-5

**Comment by kmuthukk** [comment]
Thanks @OlegLoginov !

**Comment by m-iancu** [comment]
@OlegLoginov Do we also need to update the YugaByte code to refer to the new version? 
Is that in the works? 
```
$ git grep "2.9.0-yb-4"
src/yb/integration-tests/CMakeLists.txt:set(CASS_DRIVER_VERSION "2.9.0-yb-4")
thirdparty/build_definitions/cassandra_cpp_driver.py:                'cassandra-cpp-driver', '2.9.0-yb-4',
thirdparty/thirdparty_src_checksums.txt:8f8299b59caaead1b83bda13c8f0feec652daea22d2247ff5f05cde5266c9901  cassandra-cpp-driver-2.9.0-yb-4.tar.gz
```
cc @rajukumaryb @kmuthukk

**Comment by rajukumaryb** [comment]
Thanks to @m-iancu , the following local patch seems to work -

diff --git a/src/yb/integration-tests/CMakeLists.txt b/src/yb/integration-tests/CMakeLists.txt
index 4a560c437..83c75d187 100644
--- a/src/yb/integration-tests/CMakeLists.txt
+++ b/src/yb/integration-tests/CMakeLists.txt
@@ -113,7 +113,7 @@ ADD_YB_TEST(log_version-test)

 set(YB_TEST_LINK_LIBS_SAVED ${YB_TEST_LINK_LIBS})
 set(YB_TEST_LINK_LIBS ${YB_TEST_LINK_LIBS} cassandra)
-set(CASS_DRIVER_VERSION "2.9.0-yb-4")
+set(CASS_DRIVER_VERSION "2.9.0-yb-5")
 set(CASS_DRIVER_INTERNAL_INCLUDE "${YB_THIRDPARTY_DIR}/src/cassandra-cpp-driver-${CASS_DRIVER_VERSION}/src")
 ADD_YB_TEST(cassandra_cpp_driver-test)
 target_include_directories(cassandra_cpp_driver-test PUBLIC
diff --git a/thirdparty/build_definitions/cassandra_cpp_driver.py b/thirdparty/build_definitions/cassandra_cpp_driver.py
index 0534b8c9e..826aac27f 100644
--- a/thirdparty/build_definitions/cassandra_cpp_driver.py
+++ b/thirdparty/build_definitions/cassandra_cpp_driver.py
@@ -23,7 +23,7 @@ from build_definitions import *
 class CassandraCppDriverDependency(Dependency):
     def __init__(self):
         super(CassandraCppDriverDependency, self).__init__(
-                'cassandra-cpp-driver', '2.9.0-yb-4',
+                'cassandra-cpp-driver', '2.9.0-yb-5',
                 'https://github.com/YugaByte/cassandra-cpp-driver/archive/{0}.tar.gz',
                 BUILD_GROUP_INSTRUMENTED)
         self.copy_sources = False
diff --git a/thirdparty/thirdparty_src_checksums.txt b/thirdparty/thirdparty_src_checksums.txt
index 4213133f6..ad1064303 100644
--- a/thirdparty/thirdparty_src_checksums.txt
+++ b/thirdparty/thirdparty_src_checksums.txt
@@ -1,6 +1,6 @@
 a26d338c9024eeedb68e485db0b3a25a5fa00df2c23b9453f77e712c588d3079  bitshuffle-55f9b4c.tar.gz
 8f32d4617390d1c2d16f26a27ab60d97807b35440d45891fa340fc2648b04406  boost-1.69.0.tar.bz2
-8f8299b59caaead1b83bda13c8f0feec652daea22d2247ff5f05cde5266c9901  cassandra-cpp-driver-2.9.0-yb-4.tar.gz
+a7febd0ac464878f56b0c23fce77fb54e00e048f1a84f5a64ad582ac7d57fed3  cassandra-cpp-driver-2.9.0-yb-5.tar.gz
 a45b62dde5d7d5fdcdfa876b0af92f164d434b06e9e89b5d0b1cbc65dfe3f418  cfe-7.0.1.tar.xz
 4c93c7d2bb07923a8b272da3ef7914438080aeb693725f4fc5c19cd0e2613bed  clang-tools-extra-7.0.1.tar.xz
 782edfc119ee172f169c91dd79f2c964fb6b248bd9b73523149030ed505bbe18  compiler-rt-7.0.1.tar.xz
