### ISSUE TITLE
[YSQL] compilecmds bulid is broken by 65ec75f60

### ISSUE THREAD

**Issue by abhinab-yb** [yugabyte/yugabyte-db#30726]
Jira Link: [DB-20616](https://yugabyte.atlassian.net/browse/DB-20616)
### Description

65ec75f603937d63636c1668aeeca64970b9a226 added a library yb_pgresult_util
which is used by postgres_fdw but not built in case of `ybd compilecmds --clean`

This results in a compilation failure on that build

```
/-------------------------------------------------------------------------------
| COMPILATION FAILED
|-------------------------------------------------------------------------------
ld: library 'yb_pgresult_util' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Input files:
  connection.o
  deparse.o
  option.o
  postgres_fdw.o
  shippable.o
Output file (from -o): postgres_fdw.so
\-------------------------------------------------------------------------------
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [x] I confirm this issue does not contain any sensitive information.

[DB-20616]: https://yugabyte.atlassian.net/browse/DB-20616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
