### ISSUE TITLE
Wipe-restart command does not work on 1.2.12 on RHEL

### ISSUE THREAD

**Issue by dpredhat** [YugaByte/yugabyte-db#1771]
[dodil yugabyte-1.2.12.0]$ ./bin/yb-ctl wipe_restart
Traceback (most recent call last):
  File "./bin/yb-ctl", line 1658, in <module>
    control.run()
  File "./bin/yb-ctl", line 1631, in run
    self.args.func()
  File "./bin/yb-ctl", line 1484, in wipe_restart_cmd_impl
    self.destroy()
AttributeError: ClusterControl instance has no attribute 'destroy'
^^^ Encountered errors ^^^
[dodil yugabyte-1.2.12.0]$ ^C
