### ISSUE TITLE
[YSQL] Code building is broken on MacOS after #27323

### ISSUE THREAD

**Issue by arybochkin** [yugabyte/yugabyte-db#28494]
Jira Link: [DB-18184](https://yugabyte.atlassian.net/browse/DB-18184)
### Description

Code building from scratch on MacOs started failing after [#27323](https://github.com/yugabyte/yugabyte-db/commit/ee3ebe722332ea8a5f0e6e52784e7fefcc1b70dc) has got committed:
```
rm -rf ~/code/yugabyte-db/build
./yb_build.sh --clean

-------
Result:

  cargo:warning=/-------------------------------------------------------------------------------
  cargo:warning=| COMPILATION FAILED
  cargo:warning=|-------------------------------------------------------------------------------
  cargo:warning=clang: error: no such include directory: '../../../../../code/yugabyte-db/PCRE_INCLUDE_ROOT_DIR-NOTFOUND/libpcre2-8' [-Werror,-Wmissing-include-dirs]
...
ninja: build stopped: subcommand failed.

==========================================================================================
YUGABYTE BUILD SUMMARY
==========================================================================================
Build type                       : debug
C/C++ compiler                   : clang
Build architecture               : arm64
...
Exit code                        : 1
```

MacOS version is 15.5
Chip - Apple M4 Pro

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [x] I confirm this issue does not contain any sensitive information.

[DB-18184]: https://yugabyte.atlassian.net/browse/DB-18184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by arybochkin** [comment]
This didn't help:
```
export PCRE_INCLUDE_ROOT_DIR=/opt/homebrew/include
export PCRE_LIB_ROOT_DIR=/opt/homebrew/lib

export PCRE_INCLUDE_ROOT_DIR="$(pkg-config --cflags libpcre2-8)"
export PCRE_LIB_ROOT_DIR="$(pkg-config --libs libpcre2-8)"

export PCRE_INCLUDE_ROOT_DIR="/opt/yb-build/thirdparty/yugabyte-db-thirdparty-<latest>-macos-arm64/installed/uninstrumented/include/"
export PCRE_LIB_ROOT_DIR="/opt/yb-build/thirdparty/yugabyte-db-thirdparty-<latest>-6c7155ea61-macos-arm64/installed/uninstrumented/lib"
```
