### ISSUE TITLE
[YSQL] Compile error building orafce on Ubuntu 22.04/clang12

### ISSUE THREAD

**Issue by es1024** [yugabyte/yugabyte-db#12990]
Jira Link: [DB-2717](https://yugabyte.atlassian.net/browse/DB-2717)
### Description

While trying to compile on Ubuntu 22.04/clang12, the following error appears:
```
/-------------------------------------------------------------------------------
| COMPILATION FAILED
|-------------------------------------------------------------------------------
src/postgres/third-party-extensions/orafce/pipe.c:94:3: error: redefinition of 'pipe' as different kind of symbol
} pipe;
  ^
/usr/include/unistd.h:437:12: note: previous definition is here
extern int pipe (int __pipedes[2]) __THROW __wur;
```

This appears to be fixed upstream with https://github.com/orafce/orafce/commit/1f162a6da427ae31ab0fcff8c3f0abdb3c5eddb2.

**Comment by es1024** [comment]
Fixed with 60d5a40.
