### ISSUE TITLE
libunwind multiple definition of `_U_dyn_info_list' on GCC 10

### ISSUE THREAD

**Issue by rtsisyk** [yugabyte/yugabyte-db#7249]
libunwind doesn't compile under GCC 10.  See https://github.com/libunwind/libunwind/pull/166 for details. Upgrading to libunwind 1.5.0 solves the problem.

Please update libunwind fork in https://github.com/yugabyte/libunwind to the latest 1.5.0. 
I haven't finished compiling YB yet, but I will test that it works with 1.5.0 and send a PR to this repo if some changes are needed.

[thirdparty-libunwind.patch.txt](https://github.com/yugabyte/yugabyte-db/files/5989903/thirdparty-libunwind.patch.txt)

**Comment by rtsisyk** [comment]
Update: it was GCC 10 installed via dnf install gcc gcc-c++ on Fedora 33.

**Comment by mbautin** [comment]
@rtsisyk to update libunwind, you need to update the version in the following file: https://github.com/yugabyte/yugabyte-db-thirdparty/blob/master/python/build_definitions/libunwind.py

**Comment by mbautin** [comment]
Also you will need to add the checksum to https://github.com/yugabyte/yugabyte-db-thirdparty/blob/master/thirdparty_src_checksums.txt and refresh the repository at https://github.com/yugabyte/libunwind to include the new version.

**Comment by rtsisyk** [comment]
Thanks! I will try later this week.

**Comment by mbautin** [comment]
Closing as libunwind has been updated to 1.5.0 in master.

**Comment by rzr** [comment]
Related-to: https://github.com/libunwind/libunwind/issues/154

**Comment by rtsisyk** [comment]
Thanks!
