### ISSUE TITLE
Dependency issue when building with Make on Apple M1 machine (for x86_64)

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#7629]
It looks like location.hh is not being generated in time before it is required. There is some dependency that needs to be declared somewhere.
[
 61%] Building CXX object src/yb/consensus/CMakeFiles/consensus.dir/peer_manager.cc.o
[ 61%] Building CXX object src/yb/consensus/CMakeFiles/consensus.dir/quorum_util.cc.o
[ 61%] Building CXX object src/yb/consensus/CMakeFiles/consensus.dir/raft_consensus.cc.o
[ 61%] Building CXX object src/yb/consensus/CMakeFiles/consensus.dir/replica_state.cc.o
[ 61%] Building CXX object src/yb/consensus/CMakeFiles/consensus.dir/replicate_msgs_holder.cc.o
[ 61%] Building CXX object src/yb/consensus/CMakeFiles/consensus.dir/retryable_requests.cc.o
[ 61%] Linking CXX shared library ../../../lib/libconsensus.dylib
[ 61%] Built target consensus
Scanning dependencies of target ql_util
[ 61%] Building CXX object src/yb/yql/cql/ql/util/CMakeFiles/ql_util.dir/cql_message.cc.o

( cd "/Users/yugabyte/code/yugabyte-db/build/release-clang-dynamic/src/yb/yql/cql/ql/util" && YB_THIRDPARTY_DIR=/Users/yugabyte/code/yugabyte-db-thirdparty /usr/bin/clang++ -Dql_util_EXPORTS -I/Users/yugabyte/code/yugabyte-db/build/release-clang-dynamic/src -I/Users/yugabyte/code/yugabyte-db/ent/src -I/Users/yugabyte/code/yugabyte-db/src -I/Users/yugabyte/code/yugabyte-db/build/release-clang-dynamic/postgres/include -isystem /Users/yugabyte/code/yugabyte-db-thirdparty/installed/common/include -isystem /Users/yugabyte/code/yugabyte-db-thirdparty/installed/clang_uninstrumented/include -Werror -fno-strict-aliasing -msse4.2 -Wall -Wno-sign-compare -Wno-deprecated -Winvalid-pch -pthread -DBOOST_BIND_NO_PLACEHOLDERS -DROCKSDB_PLATFORM_POSIX -DBOOST_ERROR_CODE_HEADER_ONLY -DYB_COMPILER_TYPE=clang -DYB_COMPILER_VERSION=12.0.0 -DROCKSDB_LIB_IO_POSIX -DSNAPPY -DZLIB -D__STDC_FORMAT_MACROS -Wno-deprecated-declarations -DGFLAGS=gflags -Wnon-virtual-dtor -Werror=enum-compare -Werror=reorder -Werror=switch -Werror=return-type -Werror=non-virtual-dtor -Werror=string-plus-int -Werror=return-stack-address -Werror=implicit-fallthrough -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wthread-safety-analysis -DOS_MACOSX -DYB_HEADERS_NO_STUBS=1 -O3 -g -DNDEBUG -fno-omit-frame-pointer -Wno-ambiguous-member-template -Wimplicit-fallthrough -Qunused-arguments -Wno-c++17-compat-mangling -fPIC -DTCMALLOC_ENABLED -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk -fPIC -std=gnu++14 -o CMakeFiles/ql_util.dir/cql_message.cc.o -c /Users/yugabyte/code/yugabyte-db/src/yb/yql/cql/ql/util/cql_message.cc )  # Compiler exit code: 1.

/-------------------------------------------------------------------------------
| COMPILATION FAILED
|-------------------------------------------------------------------------------
In file included from src/yb/yql/cql/ql/util/cql_message.cc:26:
In file included from src/yb/yql/cql/cqlserver/cql_processor.h:30:
In file included from src/yb/yql/cql/ql/ql_processor.h:26:
In file included from src/yb/yql/cql/ql/parser/parser.h:23:
In file included from src/yb/yql/cql/ql/parser/parse_context.h:21:
src/yb/yql/cql/ql/parser/location.h:24:10: fatal error: 'yb/yql/cql/ql/parser/location.hh' file not found
#include "yb/yql/cql/ql/parser/location.hh"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Input files:
  src/yb/yql/cql/ql/util/cql_message.cc
Output file (from -o): CMakeFiles/ql_util.dir/cql_message.cc.o
\-------------------------------------------------------------------------------
make[2]: *** [src/yb/yql/cql/ql/util/CMakeFiles/ql_util.dir/cql_message.cc.o] Error 1
make[1]: *** [src/yb/yql/cql/ql/util/CMakeFiles/ql_util.dir/all] Error 2
make: *** [all] Error 2

real	44m44.519s
user	35m15.525s
sys	7m9.128s
[2021-03-12T00:00:16 yb_build.sh:417 run_cxx_build] C++ build finished with exit code 2 (build type: release, compiler: clang). Timing information is available above.

**Comment by svarnau** [comment]
Also  reported on Centos7: https://yugabyte-db.slack.com/archives/CNVCKJGHK/p1616938173023100

**Comment by anmalysh-yb** [comment]
This is also reproducible on MacBook with Intel CPU if make build is used. Doesn't happen if building using ninja.

**Comment by mbautin** [comment]
Another report from a user:
```

**Comment by pkj415** [comment]
As a workaround, build on 2.3 first and then on master.

**Comment by svarnau** [comment]
This seems to be same bug as #8225. Fix has already been landed on master: c77d4890f0
